### PR TITLE
Let transport know that TApplicationException is about to be sent

### PR DESCRIPTION
**Pull request by alandau**
Useful if the transport needs to do something special before sending
those

### CODE REVIEW

**Comment by jesboat** [comment]
Reviewed by: jsailor

Would it make more sense for the transport to have TException in general, not just TAE?

**Comment by alandau** [comment]
Not sure, TAE is the only exception type that is serialized, and so is transparent to the transport layer. With this diff we notify the transport layer about a TAE.
For non-TAE, they are sent to the transport layer as exceptions, so no additional notification is needed

**Comment by jesboat** [comment]
Hmm.

What about in THeaderProtocol.writeMessageBegin when the message has TMessageType.EXCEPTION? I think that handles exactly the things which are currently missing uex/uexw, and gets it for Nifty, Nifty+Swift, and Nifty-fbcode in a single place.

**Comment by alandau** [comment]
That's interesting, I'll investigate

**Comment by alandau** [comment]
Well, the bad part is that althougt we can get a notification through writeMessageBegin that a TAE is about to be written, we don't know its value (aka message string). We can't change writeMessageBegin to pass this info (this would require a lot more changes). Do you see a way around this?

**Comment by jesboat** [comment]
I don't see a good way around that. Changes to writeMessageBegin would work, but would be pretty invasive for a relatively niche feature. Another option would be to have THeaderProtocol note that the TMessage is TMessageType.EXCEPTION, and then deserialize the TAE out of the output buffer to get the info at flush time, but that's pretty disgusting.

Possibly adding the "exception thrown by this call" field to the RequestContext would be conceptually cleaner than adding it to the TNiftyTransport? But I don't know off the top of my head if the RequestContext is easily available everywhere we'd need it.

I am (still) fine with landing this series as-is.

**Comment by alandau** [comment]
OK, will land as is to unblock people. Once the repos are unified, it'll be easier to do cross-project API changes

**Pull request merged**
